# aenvironment

```{r, eval=TRUE, include=FALSE}
library(htmltools)
```

```{r, echo=FALSE}
div(
  class = "row",
  div(
    class = "col-md-3",
    img(src = "logo.png")
  ),
  div(
    class = "col-md-9",
    "Environments for",
    tags$a(
      href = "https://aframer.john-coene.com",
      target = "_blank",
      "aframer"
    )
  )
)
```

## Installation

You can install the released version of aenvironment from [CRAN](https://CRAN.R-project.org) with:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("JohnCoene/aenvironment")
```

## Presets

18 built-in presets.

- `none`
- `default`
- `contact`
- `egypt`
- `checkerboard`
- `forest`
- `goaland`
- `yavapai`
- `goldmine`
- `threetowers`
- `poison`
- `arches`
- `tron`
- `japan`
- `dream`
- `volcano`
- `starry`
- `osiris`

## Example

```{r}
library(aframer)
library(aenvironment)

embed_aframe(
  a_scene(
    a_dependency(),
    aenvironment_dependency(),
    a_environment(
      environment = aframer::opts_aframe(
        preset = "forest"
      )
    )
  )
)
```

